import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ClientLayout } from "./client-layout";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] gap-4 w-full h-screen p-4 sm:p-8 md:p-4 overflow-auto">
            <a
              className="block md:hidden bg-black text-white absolute transform -translate-x-full transition-transform duration-500 focus:translate-x-0"
              href="#skip"
            >
              Skip to Content
            </a>
            <Sidebar />
            <ClientLayout>{children}</ClientLayout>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
